config/routes.rb
Rails.application.routes.draw do

  resources :sports do
    resources :leagues
  end

  resources :leagues do
    resources :matches
  end

  resources :predictions

  resources :tweets

  devise_for :users

  get 'shop/index'

    get 'twitter/index'

  root to: "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/league.rb
class League < ApplicationRecord
  belongs_to :sport, optional: true
  has_many :matches
  has_and_belongs_to_many :teams
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :league, optional: true
  belongs_to :sport, optional: true
  belongs_to :venue, optional: true
  has_many :predictions
  has_many :questions
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :team
end

app/models/prediction.rb
class Prediction < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :match, optional: true
  belongs_to :sport, optional: true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :match, optional: true
  belongs_to :prediction, optional: true
end

app/models/sport.rb
class Sport < ApplicationRecord
  has_many :leagues
  has_many :teams
  has_many :matches, through: :leagues
  has_many :predictions, through: :matches
end

app/models/team.rb
class Team < ApplicationRecord
  has_and_belongs_to_many :leagues
  belongs_to :sport, optional: true
  belongs_to :match, optional: true
  has_many :players
end

app/models/twitter_adapter.rb
module TwitterAdapter

  def self.search(search_string)

    bearer_token = generate_bearer_token
    search_string.gsub(/\s+/, "%20")

    # URL = https://api.twitter.com... (Key is "how to find resource")
    # URN = tweets.json (What the thing is that we're actually looking for)
    # URI = Both of the above since they both describe the resource we're trying to retrieve

    url = URI("https://api.twitter.com/1.1/search/tweets.json?q=%2523#{search_string}&result_type=recent&tweet_mode=extended")

    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = true

    # DON'T DO THIS IN PRACTICE!!
    # Should be something more like...
    #
    # http.use_ssl = true
    # pem = File.read("/path/to/my.pem")
    # http.cert = OpenSSL::X509::Certificate.new(pem)
    # http.key  = OpenSSL::PKey::RSA.new(pem)
    # http.verify_mode = OpenSSL::SSL::VERIFY_PEER

    http.verify_mode = OpenSSL::SSL::VERIFY_NONE

    request = Net::HTTP::Get.new(url)
    request["authorization"] = "Bearer #{bearer_token}"

    # binding.pry

    response = JSON.parse(http.request(request).read_body)["statuses"].map { |result| result }

  end

private

  def self.generate_bearer_token

    url = URI("https://api.twitter.com/oauth2/token")

    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE

    consumer_key    = ENV["TWITTER_CONSUMER_KEY"]
    consumer_secret = ENV["TWITTER_CONSUMER_SECRET"]

    bearer_token_credentials = Base64.strict_encode64("#{consumer_key}:#{consumer_secret}")

    request = Net::HTTP::Post.new(url)
    request["authorization"] = "Basic #{bearer_token_credentials}"
    request["content-type"] = 'application/x-www-form-urlencoded;charset=UTF-8'
    request.body = "grant_type=client_credentials"

    response = JSON.parse http.request(request).read_body
    response["access_token"]

  end

end









# twitter gem stuff

# client = Twitter::REST::Client.new do |config|
# config.consumer_key    = "YOUR_CONSUMER_KEY"
# config.consumer_secret = "YOUR_CONSUMER_SECRET"
# end

# config = {
#   consumer_key:    "YOUR_CONSUMER_KEY",
#   consumer_secret: "YOUR_CONSUMER_SECRET",
# }
#
# client = Twitter::REST::Client.new(config)



# client.user("backcourtdribbl")

# puts client.bearer_token

  # client.search("to:USWNT", result_type: "recent").take(5).each
  #   do |tweet|
  #     puts tweet.text
  # end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :predictions



 private
 def calculate_percent_correct_predictions
   correct_predictions = self.predictions.where(correct?: true).count
   total_predictions = self.predictions.count

   percent_correct = (correct_predictions.to_f / total_predictions.to_f) * 100

   percent_correct.to_i
 end

end

app/models/venue.rb
class Venue < ApplicationRecord
  belongs_to :match, optional: true
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/shop_controller.rb
class ShopController < ApplicationController
  def index
  end
end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  def index
    @sports = Sport.all 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
  # def find_future_matches(matches)
  # #Returns an array of future matches
  #   matches.select{|match| match.start_time > Time.now && match.start_date > Date.today}
  # end

  def format_match_date(match)
    match_date = match.start_date
    match_date.strftime("%m/%d/%Y at %I:%M%p")
  end

  def format_match_date_english(match)
     date = match.start_date.strftime("%B #{match.start_date.day.ordinalize}, %Y")
     time = match.start_time.strftime("%I:%M%p")
     "#{date} at #{time}"
  end

  def sort_matches_by_date(matches)
    matches.sort_by{ |match| match.start_date }
  end
end

app/helpers/predictions_helper.rb
module PredictionsHelper
  def select_team_predictions(match, team)
    predictions = match.predictions.select {|prediction| prediction.guess == team.name }
  end

  def select_tie_predictions(match, keyword)
    predictions = match.predictions.select {|prediction| prediction.guess == keyword }
    # predictions.count
  end

  # def build_prediction_types_array(home, team, tie)
  #   array = [home, team, tie]
  # end

  def calculate_total_predictions(match)
    match.predictions.count.to_f
  end

  def calculate_team_prediction_percentage(match, guess)
    predictions = select_team_predictions(match, guess)
    total_predictions = predictions.count
    if total_predictions > 0
      percentage_of_predictions = ((total_predictions.to_f / calculate_total_predictions(match)) * 100).to_i
      format_percent(percentage_of_predictions)
    else
      "There are no predictions for this outcome yet!"
    end
  end

  def calculate_tie_prediction_percentage(match, guess)
    predictions = select_tie_predictions(match, guess)
    total_predictions = predictions.count
    if total_predictions > 0
      percentage_of_predictions = ((total_predictions.to_f / calculate_total_predictions(match)) * 100).to_i
      format_percent(percentage_of_predictions)
    else
      "There are no predictions for this outcome yet!"
    end
  end

  def format_percent(num)
    "#{num}%"
  end

  def pluralize_prediction_statement(num_predictions)
    if num_predictions > 1
      "users predict"
    else
      "user predicts"
    end
  end
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/twitter_helper.rb
module TwitterHelper
end

app/views/home/index.html.erb
<div class="home-menu-area">
    <div class="home-nav">
      <div class="nav-row">
        <div class="action-button left">
          <div class="action-title">
            <%= link_to 'Wall', tweets_path(:keyword => "woso"), class: "orange" %>
          </div>
          <div class="action-subtext">
            exploring the twitterverse for key words for woman's soccer
          </div>
        </div>
        <div class="action-button right">
          <div class="action-title">
            <%= link_to 'Dribble', sports_path, class:"green-ish" %>
          </div>
          <div class="action-subtext">
            make predictions and engage with WoSo statistics
          </div>
        </div>
      </div>

      <div class="nav-row">
        <div class="action-button left">
          <div class="action-title">
            <%= link_to 'Twitter', "https://rawgit.com/femaleinventor/Hackathon_Dribble/development/sentiment/sentiment.html", class:"blue" %>
          </div>
          <div class="action-subtext">
            collecting currents tweets from teams around the world
          </div>
        </div>
        <div class="action-button right">
          <div class="action-title">
            <!-- <%= link_to 'Shop', shop_index_path, class:"wall" %> -->
            <%= link_to shop_index_path, class: "orange" do %>
              Sh<span class='blue'>o</span>p
            <% end %>

          </div>
          <div class="action-subtext">
            cool stuff made by or about female athletes (coming soon)
          </div>
        </div>
      </div>

    </div>
  </div>

app/views/shop/index.html.erb
<%= render "shared/site_nav" %>

<div class="items-index">
  <div class="shop-item"> Store Item 1</div>
  <div class="shop-item"> Store Item 2</div>
  <div class="shop-item"> Store Item 3</div>
  <div class="shop-item"> Store Item 4</div>
  <div class="shop-item"> Store Item 5</div>
  <div class="shop-item"> Store Item 6</div>
  <div class="shop-item"> Store Item 7</div>
  <div class="shop-item"> Store Item 8</div>
  <div class="shop-item"> Store Item 9</div>
  <div class="shop-item"> Store Item 10</div>
  <div class="shop-item"> Store Item 11</div>
  <div class="shop-item"> Store Item 12</div>
  <div class="shop-item"> Store Item 13</div>
  <div class="shop-item"> Store Item 14</div>
  <div class="shop-item"> Store Item 15</div>
  <div class="shop-item"> Store Item 16</div>
  <div class="shop-item"> Store Item 17</div>
  <div class="shop-item"> Store Item 18</div>
  <div class="shop-item"> Store Item 19</div>
  <div class="shop-item"> Store Item 20</div>
</div>